org: mpepe66
app: hello-evo
service: hello-evo
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
